Rewrite some code

diff --git a/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku b/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku
--- a/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku
+++ b/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku
@@ -1,32 +1,83 @@
 #!/data/data/com.termux/files/usr/bin/bash
 
-if [ ! -f "$PREFIX/shizuku/shizuku_functions.sh" ]; then
-    echo 'shizuku_functions.sh file not found. Please reinstall package!'
+if [[ ! -f "$PREFIX/libexec/shizuku/shizuku_lib.sh" ]]; then
+    echo "Error: File $PREFIX/libexec/shizuku/shizuku_lib.sh not found"
+    echo "Please reinstall termux-shizuku-tools package"
     exit 1
 fi
 
-. $PREFIX/shizuku/shizuku_functions.sh
+source $PREFIX/libexec/shizuku/shizuku_lib.sh
 
-THIS_PKG_PATH=$(termux_shizuku_tools_directory)
-
-if [ ! -f "$THIS_PKG_PATH/rish" ]; then
-    echo 'rish file not found. Please reinstall package!'
+if [[ ! -f "$SHIZUKU_LIB_DIR/termux_shizuku_tools_utils.sh" ]]; then
+    echo "Error: File $SHIZUKU_LIB_DIR/termux_shizuku_tools_utils.sh not found"
+    echo "Please reinstall termux-shizuku-tools package"
     exit 1
 fi
 
-if [ ! -f "$THIS_PKG_PATH/rish_shizuku.dex" ]; then
-    echo 'rish_shizuku.dex file not found. Please reinstall package!'
+source $SHIZUKU_LIB_DIR/termux_shizuku_tools_utils.sh
+
+if [[ ! -f "$RISH_DEX_PATH" ]]; then
+    echo "Error: File $RISH_DEX_PATH not found"
+    echo "Please reinstall termux-shizuku-tools package"
     exit 1
 fi
 
-if [ $(is_shizuku_installed) = "false" ]; then
-   echo "Shizuku not installed!"
-   exit 1
-fi
-
-if [ $# -gt 0 ]; then
+if [[ -z "$1" ]]; then
+   show_help
+    
+elif [[ "$1" == "info" || "$1" == "i" ]]; then
+    echo "Is Shizuku installed: $(is_shizuku_installed)"
+    echo "Shizuku version code: $(shizuku_version_code)"
+    echo "Is Shizuku server running: $(is_shizuku_server_running)"
+    exit 0
+    
+elif [[ "$1" == "open" || "$1" == "o" ]]; then
+    if [[ "$(is_shizuku_installed)" ==  "false" ]]; then
+        echo "Error: Shizuku is not installed"
+        exit 1
+        fi
+    echo "Launching Shizuku app..."
+    open_shizuku
+    exit 0
+    
+elif [[ "$1" == "stop" || "$1" == "s" ]]; then
+    if [[ "$(is_shizuku_installed)" ==  "false" ]]; then
+        echo "Error: Shizuku is not installed"
+        exit 1
+        fi
+    echo "Stopping Shizuku server..."
+    stop_shizuku_server
+    exit 0
+    
+elif [[ "$1" == "help" || "$1" == "h" || "$1" == "--help" || "$1" == "-h" ]]; then
+    show_help
+    exit 0
+    
+elif [[ "$1" == "shell" || "$1" == "sh" ]]; then
+    if [[ "$(is_shizuku_installed)" ==  "false" ]]; then
+        echo "Error: Shizuku is not installed"
+        exit 1
+        fi
+    echo "Starting Shizuku interactive shell..."
+    echo "Type 'exit' to exit from interactive Shizuku shell"
+    open_shizuku_interactive_shell
+    exit 0
+    
+elif [[ "$1" == "execute" || "$1" == "exec" || "$1" == "e" ]]; then
+    if [[ "$(is_shizuku_installed)" ==  "false" ]]; then
+        echo "Error: Shizuku is not installed"
+        exit 1
+        fi
+    shift
     execute_shizuku_command "$@"
+    exit 0
+    
+elif [[ "$1" == "version" || "$1" == "v" ]]; then
+    show_version
+    exit 0
+    
 else
-    echo "Trying to run Shizuku mode..."
-    sh $THIS_PKG_PATH/rish
+    echo "Unknown command: $1"
+    echo "Use 'shizuku help' for available commands"
+    exit 1
 fi
