Update shizuku-info

diff --git a/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku-info b/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku-info
--- a/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku-info
+++ b/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku-info
@@ -1,5 +1,10 @@
 #!/data/data/com.termux/files/usr/bin/sh
 
+if [ ! -f "$PREFIX/shizuku/shizuku_functions.sh" ]; then
+    echo 'shizuku_functions.sh file not found. Please reinstall package!'
+    exit 1
+fi
+
 . $PREFIX/shizuku/shizuku_functions.sh
 
 THIS_PKG_DIR=$(termux_shizuku_tools_directory)
