Update shizuku-open

diff --git a/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku-open b/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku-open
--- a/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku-open
+++ b/termux-shizuku-tools/data/data/com.termux/files/usr/bin/shizuku-open
@@ -1,5 +1,10 @@
 #!/data/data/com.termux/files/usr/bin/sh
 
+if [ ! -f "$PREFIX/shizuku/shizuku_functions.sh" ]; then
+    echo 'shizuku_functions.sh file not found. Please reinstall package!'
+    exit 1
+fi
+
 . $PREFIX/shizuku/shizuku_functions.sh
 
 if [ $(is_shizuku_installed) = "true" ]; then
